### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by tobihaze** [tobihaze/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振舞に多くの人が癒やされています。'

**Comment by tobihaze** [comment]
これから対応します。

**Comment by suzugumi** [comment]
ｖ（ ・`ー・´）ｖ

**Comment by tobihaze** [comment]
204cc76277899954d119d1c344a1327b72cdef3a にて対応しました。
